$(document).ready(function(){
    $("#dropdown1").click(function(){
        $("#model1").toggle();
        
    });
    $("#dropdown2").click(function(){
        $("#model2").toggle();
    });

    $("#car1").hover(function(){
        $("#car1>.details").toggle();
    })
    $("#car2").hover(function(){
        $("#car2>.details").toggle();
    })
    $("#car3").hover(function(){
        $("#car3>.details").toggle();
    })
    $("#car4").hover(function(){
        $("#car4>.details").toggle();
    })
    $("#car5").hover(function(){
        $("#car5>.details").toggle();
    })
    $("#car6").hover(function(){
        $("#car6>.details").toggle();
    })
    $("#car7").hover(function(){
        $("#car7>.details").toggle();
    })
    $("#car8").hover(function(){
        $("#car8>.details").toggle();
    })
    $("#car9").hover(function(){
        $("#car9>.details").toggle();
    })
    $("#car10").hover(function(){
        $("#car10>.details").toggle();
    })
    $("#car11").hover(function(){
        $("#car11>.details").toggle();
    })
    $("#car12").hover(function(){
        $("#car12>.details").toggle();
    })
    
})